name: Build Flutter App (Staging)

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK for Staging
        run: flutter build apk --flavor staging -t lib/main_staging.dart

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: staging-apk
          path: build/app/outputs/flutter-apk/app-staging-release.apk
